plugins {
    id 'com.android.library'
    id 'expo-module-gradle-plugin'
}

group = 'com.speedshield.rnssh'
version = '2.0.0'

android {
    namespace 'com.speedshield.rnssh'

    defaultConfig {
        versionCode 1
        versionName "1.0"
    }
    lintOptions {
        abortOnError false
    }
}

dependencies {
    implementation 'org.bouncycastle:bcprov-jdk15on:1.70'
    api 'com.github.mwiede:jsch:0.2.17'
}
